Repository 2025-toss-project/Front-end, pull requests merged in 2025-03, with the labels that each got.

#24 [Style-21] 지출장소검색 퍼블리싱
  src/App.tsx
  src/components/AddPayInput.tsx
  src/components/SearchPlace.tsx
  src/components/common/Buttons.tsx
  src/components/common/InputDefault.tsx
  src/components/sections/SearchListSection.tsx
  src/contexts/SearchPlaceContext.tsx
  src/pages/AddPayPage.tsx
  src/pages/MapPinPage.tsx
  src/pages/MyPage.tsx
  src/pages/SearchPlacePage.tsx
  tailwind.config.js
Labels: style

#29 Style/10
  src/App.tsx
  src/components/BudgetStatus.tsx
  src/components/CategoryStatus.tsx
  src/components/MonthlyBudget.tsx
  src/pages/BudgetManage.tsx
  src/pages/BudgetManageSet.tsx
Labels: style

#30 [STYLE-23] 통계 페이지 퍼블리싱 및 전체 수정
  package-lock.json
  package.json
  src/App.tsx
  src/components/charts/BarChart.tsx
  src/components/charts/DoughnutChart.tsx
  src/components/charts/ProgressBarChart.tsx
  src/components/common/Header.tsx
  src/components/common/Navbar.tsx
  src/constants/NavItem.ts
  src/constants/PageUrls.tsx
  src/hooks/usePageUpdate.ts
  src/layouts/HeaderLayout.tsx
  src/layouts/MainLayout.tsx
  src/layouts/NavBarLayout.tsx
  src/pages/MainPage.tsx
  src/pages/StatisticPage.tsx
Labels: style

#32 [STYLE-10] 목표예산관리/설정 페이지 퍼블리싱
  src/components/BudgetStatus.tsx
  src/components/HalfCircleGauge.tsx
  src/pages/BudgetManage.tsx
  src/pages/BudgetManageSet.tsx
Labels: style

#34 [STYLE-11]막대그래프 컴포넌트
  src/components/BarGraph.tsx
  src/components/CategoryStatus.tsx
  src/pages/BudgetManageSet.tsx
Labels: style

#36 [STYLE-31] 지도 정보 띄우기 및 아이콘 리스트 변경
  src/components/MapBubble.tsx
  src/components/MapIconMarker.tsx
  src/components/PayList.tsx
  src/components/SelectCategory.tsx
  src/components/common/Navbar.tsx
  src/components/maps/KakaoMap.tsx
  src/components/maps/MapBottom.tsx
  src/components/maps/MapHeader.tsx
  src/constants/category.tsx
  src/hooks/useGetMyCurrentLocation.ts
  src/layouts/NavBarLayout.tsx
  src/pages/BudgetManageSet.tsx
  src/pages/MainPage.tsx
  src/stores/mapInfo.tsx
Labels: style

#39 [CHORE-37] API 연동을 위한 설정
  src/utils/api.ts
  tsconfig.json
  vite.env.d.ts
Labels: chore

#42 [FEAT_40] 로그인/회원가입 API 연동
  src/components/AddPayInput.tsx
  src/components/SelectAgeGroup.tsx
  src/components/common/InputDefault.tsx
  src/components/sections/PayTypeSection.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/SearchLocation.tsx
  src/pages/SignupPage.tsx
  src/stores/signupInfo.tsx
  src/utils/api.ts
Labels: feat

#45 [STYLE-35] 캘린더 구현
  src/assets/css/CustomCalendar.css
  src/components/AddPayInput.tsx
  src/components/CustomCalendar.tsx
  src/components/MapBubble.tsx
  src/components/PayList.tsx
  src/components/common/Buttons.tsx
  src/components/maps/MapBottom.tsx
  src/constants/NavItem.ts
  src/pages/PayRecodePage.tsx
  src/utils/formatFunc.ts
Labels: style

#50 [FEAT-48] 통계 페이지 api 연동
  src/components/charts/BarChart.tsx
  src/components/charts/DoughnutChart.tsx
  src/pages/StatisticPage.tsx
Labels: feat

#49 [FEAT-41] 소비기록 관련 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/categoryIcons/IconAll.tsx
  src/components/AddPayInput.tsx
  src/components/CustomCalendar.tsx
  src/components/PayInput.tsx
  src/components/PayList.tsx
  src/components/SearchPlace.tsx
  src/components/SelectCategory.tsx
  src/components/common/Buttons.tsx
  src/components/common/InputDefault.tsx
  src/components/common/Navbar.tsx
  src/components/maps/MapHeader.tsx
  src/constants/NavItem.ts
  src/constants/PageUrls.tsx
  src/contexts/SearchPlaceContext.tsx
  src/hooks/usePageUpdate.ts
  src/index.css
  src/pages/AddPayPage.tsx
  src/pages/PayDetailPage.tsx
  src/pages/PayRecodePage.tsx
  src/pages/SearchPlaceMapPage.tsx
  src/pages/SearchPlacePage.tsx
  src/spendingData.ts
  src/stores/CalendarInfo.tsx
  src/stores/addpayInfo.tsx
  src/stores/categoryInfo.tsx
  src/stores/placeInfo.tsx
  src/stores/spendingInfo.tsx
  src/utils/formatFunc.ts
Labels: feat

#52 [FEAT-46] 지도 api 연동
  package-lock.json
  package.json
  src/assets/payTypeIcons/IconMyPay.tsx
  src/components/MapBubble.tsx
  src/components/maps/KakaoMap.tsx
  src/components/maps/MapBottom.tsx
  src/components/maps/MapHeader.tsx
  src/constants/payType.tsx
  src/hooks/useGetMyCurrentLocation.ts
  src/hooks/useMovePage.ts
  src/pages/MainPage.tsx
  src/pages/PayDetailPage.tsx
  src/pages/SearchLocation.tsx
  src/stores/mapInfo.tsx
Labels: feat

#56 [FEAT-44] 토큰 컨트롤
  src/App.tsx
  src/apis/BudgetInfo.tsx
  src/apis/BudgetUpdate.tsx
  src/apis/ProfileUpdate.tsx
  src/apis/userInfo.tsx
  src/components/BudgetStatus.tsx
  src/components/CategoryBudgetInput.tsx
  src/components/CategoryStatus.tsx
  src/components/TypeTab.tsx
  src/components/charts/HalfDoughnutChart.tsx
  src/components/loading.tsx
  src/pages/BudgetManage.tsx
  src/pages/BudgetManageSet.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/stores/user.tsx
  src/stores/userInfo.tsx
  src/utils/api.ts
Labels: feat

#58 [FEAT-44] 지도 세부 수정
  src/components/MapBubble.tsx
  src/components/maps/KakaoMap.tsx
  src/components/maps/MapBottom.tsx
  src/components/maps/MapHeader.tsx
  src/pages/MainPage.tsx
  src/utils/api.ts
Labels: feat

#60 [FEAT-59] 지도에 carousel 추가
  package-lock.json
  package.json
  src/assets/css/carousel.css
  src/components/maps/KakaoMap.tsx
  src/components/maps/MapBottom.tsx
  src/hooks/useGetMyCurrentLocation.ts
  src/pages/MainPage.tsx
Labels: feat

#61 [STYLE-57] 회원가입 스타일 변경 및 통계, 마이페이지 주소 API연동
  src/apis/ProfileUpdate.tsx
  src/apis/userInfo.tsx
  src/components/BarGraph.tsx
  src/components/BudgetStatus.tsx
  src/components/HalfCircleGauge.tsx
  src/components/charts/BarChart.tsx
  src/components/common/InputDefault.tsx
  src/hooks/useMovePage.ts
  src/pages/BudgetManage.tsx
  src/pages/BudgetManageSet.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/pages/SearchLocation.tsx
  src/pages/SignupPage.tsx
  src/pages/StatisticPage.tsx
  src/stores/signupInfo.tsx
  src/stores/user.tsx
  src/utils/api.ts
Labels: style

#66 [FEAT-62] 로그인 안했을 경우 처리
  src/App.tsx
  src/assets/IconError.tsx
  src/pages/ErrorPage.tsx
  src/routers/PrivateRoute.tsx
Labels: feat

#72 [FIX-70] 회원가입 주소 오류
  .gitignore
  src/apis/ProfileUpdate.tsx
  src/components/CategoryBudgetInput.tsx
  src/hooks/useMovePage.ts
  src/pages/BudgetManageSet.tsx
  src/pages/LoginPage.tsx
  src/pages/SearchLocation.tsx
  src/pages/SignupPage.tsx
  src/stores/signupInfo.tsx
  src/utils/api.ts
Labels: fix

#76 [FEAT-74] 뒤로가기 기능 수정
  src/components/common/Header.tsx
  src/hooks/usePageUpdate.ts
Labels: feat

#78 [FEAT-71] 로딩창 추가
  .gitignore
  src/apis/ProfileUpdate.tsx
  src/components/BudgetStatus.tsx
  src/components/TypeTab.tsx
  src/components/charts/BarChart.tsx
  src/components/charts/DoughnutChart.tsx
  src/components/maps/KakaoMap.tsx
  src/pages/BudgetManage.tsx
  src/pages/BudgetManageSet.tsx
  src/pages/MyPage.tsx
  src/pages/StatisticPage.tsx
Labels: feat

#79 [FIX/77] 장소검색 UI 깨짐, 마커 삭제
  package.json
  src/hooks/useMovePage.ts
  src/hooks/usePageUpdate.ts
  src/pages/SearchPlaceMapPage.tsx
  src/pages/SearchPlacePage.tsx
Labels: fix

#90 fix : 회원 정보 삭제
  src/hooks/useMovePage.ts
Labels: fix
